spring:
  application:
    name: carts-service
  datasource:
    url: jdbc:h2:file:./data/webposDB;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}