spring:
  datasource:
    url: jdbc:h2:file:./data/webposDB;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datesource-initialization: true
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  batch:
    jdbc:
      initialize-schema: always